// <auto-generated />
using System;
using DotNetProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetProject.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorName = "Jennifer Aniston",
                            Description = "Initially a waitress at Central Perk, later becomes a fashion executive at Ralph Lauren.",
                            ImageUrl = "/img/friends/rachel.jpg",
                            Name = "Rachel Green",
                            Occupation = "Fashion Executive",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Rachel%20Green%20Friends%20best%20moments"
                        },
                        new
                        {
                            Id = 2,
                            ActorName = "Courteney Cox",
                            Description = "A perfectionist chef known for her cleanliness obsession and competitive nature.",
                            ImageUrl = "/img/friends/monica.jpg",
                            Name = "Monica Geller",
                            Occupation = "Head Chef",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Monica%20Geller%20Friends%20kitchen%20scenes"
                        },
                        new
                        {
                            Id = 3,
                            ActorName = "Lisa Kudrow",
                            Description = "A quirky masseuse and musician known for her song 'Smelly Cat'.",
                            ImageUrl = "/img/friends/phoebe.jpg",
                            Name = "Phoebe Buffay",
                            Occupation = "Masseuse/Musician",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Phoebe%20Buffay%20Smelly%20Cat"
                        },
                        new
                        {
                            Id = 4,
                            ActorName = "Matt LeBlanc",
                            Description = "A lovable but dim-witted aspiring actor best known for his role as Dr. Drake Ramoray.",
                            ImageUrl = "/img/friends/joey.jpg",
                            Name = "Joey Tribbiani",
                            Occupation = "Actor",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Joey%20Tribbiani%20how%20you%20doin"
                        },
                        new
                        {
                            Id = 5,
                            ActorName = "Matthew Perry",
                            Description = "Known for his sarcastic wit and comedic timing. Later transitions to advertising.",
                            ImageUrl = "/img/friends/chandler.jpg",
                            Name = "Chandler Bing",
                            Occupation = "IT Procurement/Advertising",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Chandler%20Bing%20sarcasm"
                        },
                        new
                        {
                            Id = 6,
                            ActorName = "David Schwimmer",
                            Description = "Monica's older brother, a paleontologist who has been married three times.",
                            ImageUrl = "/img/friends/ross.jpg",
                            Name = "Ross Geller",
                            Occupation = "Paleontologist",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Ross%20Geller%20pivot%20scene"
                        });
                });

            modelBuilder.Entity("DotNetProject.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rachel runs away from her wedding and moves in with Monica.",
                            EpisodeNumber = 1,
                            ImageUrl = "/img/friends/ep-s01e01.jpg",
                            Season = 1,
                            Title = "The One Where Monica Gets a Roommate",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Friends%20S01E01%20pilot%20clip"
                        },
                        new
                        {
                            Id = 2,
                            AirDate = new DateTime(1994, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ross finds out his ex-wife Carol is pregnant with his baby.",
                            EpisodeNumber = 2,
                            ImageUrl = "/img/friends/ep-s01e02.jpg",
                            Season = 1,
                            Title = "The One with the Sonogram at the End",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Friends%20sonogram%20episode"
                        },
                        new
                        {
                            Id = 3,
                            AirDate = new DateTime(1994, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A power outage in New York City leads to adventures for the group.",
                            EpisodeNumber = 7,
                            ImageUrl = "/img/friends/ep-s01e07.jpg",
                            Season = 1,
                            Title = "The One with the Blackout",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Friends%20blackout%20episode"
                        },
                        new
                        {
                            Id = 4,
                            AirDate = new DateTime(1995, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ross discovers Rachel's feelings for him through a drunken voicemail.",
                            EpisodeNumber = 7,
                            ImageUrl = "/img/friends/ep-s02e07.jpg",
                            Season = 2,
                            Title = "The One Where Ross Finds Out",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Friends%20Ross%20finds%20out%20episode"
                        },
                        new
                        {
                            Id = 5,
                            AirDate = new DateTime(1996, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The gang watches Rachel and Monica's prom video, revealing Ross's long-time love for Rachel.",
                            EpisodeNumber = 14,
                            ImageUrl = "/img/friends/ep-s02e14.jpg",
                            Season = 2,
                            Title = "The One with the Prom Video",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Friends%20prom%20video%20episode"
                        },
                        new
                        {
                            Id = 6,
                            AirDate = new DateTime(1996, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ross struggles to get everyone ready for a museum event.",
                            EpisodeNumber = 2,
                            ImageUrl = "/img/friends/ep-s03e02.jpg",
                            Season = 3,
                            Title = "The One Where No One's Ready",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Friends%20no%20ones%20ready%20episode"
                        });
                });

            modelBuilder.Entity("DotNetProject.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "90 Bedford Street, New York",
                            Description = "The iconic coffee house where the friends spend most of their time.",
                            ImageUrl = "/img/friends/location-central-perk.jpg",
                            Name = "Central Perk",
                            Type = "Coffee Shop",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Central%20Perk%20set%20tour"
                        },
                        new
                        {
                            Id = 2,
                            Address = "90 Bedford Street, Apt 20, New York",
                            Description = "Monica's purple-walled apartment where most scenes take place.",
                            ImageUrl = "/img/friends/location-monicas-apartment.jpg",
                            Name = "Monica's Apartment",
                            Type = "Apartment",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Monica%20Geller%20apartment%20tour"
                        },
                        new
                        {
                            Id = 3,
                            Address = "90 Bedford Street, Apt 19, New York",
                            Description = "The apartment across the hall from Monica's, featuring the famous foosball table.",
                            ImageUrl = "/img/friends/location-joey-chandler-apartment.jpg",
                            Name = "Joey & Chandler's Apartment",
                            Type = "Apartment",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Joey%20and%20Chandler%20apartment%20tour"
                        },
                        new
                        {
                            Id = 4,
                            Address = "New York",
                            Description = "Ross's various apartments throughout the series.",
                            ImageUrl = "/img/friends/location-ross-apartment.jpg",
                            Name = "Ross's Apartment",
                            Type = "Apartment",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Ross%20Geller%20apartment%20tour"
                        },
                        new
                        {
                            Id = 5,
                            Address = "New York",
                            Description = "Where Ross works as a paleontologist.",
                            ImageUrl = "/img/friends/location-museum.jpg",
                            Name = "Museum of Prehistoric History",
                            Type = "Workplace",
                            VideoUrl = "https://www.youtube.com/embed?listType=search&list=Friends%20museum%20set%20tour"
                        });
                });

            modelBuilder.Entity("DotNetProject.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 6,
                            Context = "Ross's famous catchphrase about his relationship with Rachel",
                            EpisodeId = 1,
                            Text = "We were on a break!"
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 4,
                            Context = "Joey's signature pickup line",
                            EpisodeId = 1,
                            Text = "How you doin'?"
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 5,
                            Context = "Chandler's sarcastic observation",
                            EpisodeId = 1,
                            Text = "Could this BE any more awkward?"
                        },
                        new
                        {
                            Id = 4,
                            CharacterId = 2,
                            Context = "Janice's iconic catchphrase, often imitated by others",
                            EpisodeId = 2,
                            Text = "Oh. My. God!"
                        },
                        new
                        {
                            Id = 5,
                            CharacterId = 3,
                            Context = "Phoebe explaining Ross and Rachel's relationship",
                            EpisodeId = 5,
                            Text = "See, he's her lobster!"
                        },
                        new
                        {
                            Id = 6,
                            CharacterId = 6,
                            Context = "Ross trying to move a couch up the stairs",
                            EpisodeId = 6,
                            Text = "PIVOT! PIVOT! PIVOT!"
                        });
                });

            modelBuilder.Entity("DotNetProject.Models.Quote", b =>
                {
                    b.HasOne("DotNetProject.Models.Character", "Character")
                        .WithMany("Quotes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetProject.Models.Episode", "Episode")
                        .WithMany("Quotes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("DotNetProject.Models.Character", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("DotNetProject.Models.Episode", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
